% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\newenvironment{Shaded}{}{}
\newcommand{\AlertTok}[1]{\textbf{#1}}
\newcommand{\AnnotationTok}[1]{\textit{#1}}
\newcommand{\AttributeTok}[1]{#1}
\newcommand{\BaseNTok}[1]{#1}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textit{#1}}
\newcommand{\CommentVarTok}[1]{\textit{#1}}
\newcommand{\ConstantTok}[1]{#1}
\newcommand{\ControlFlowTok}[1]{\textbf{#1}}
\newcommand{\DataTypeTok}[1]{\underline{#1}}
\newcommand{\DecValTok}[1]{#1}
\newcommand{\DocumentationTok}[1]{\textit{#1}}
\newcommand{\ErrorTok}[1]{\textbf{#1}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{#1}
\newcommand{\FunctionTok}[1]{#1}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textit{#1}}
\newcommand{\KeywordTok}[1]{\textbf{#1}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{#1}
\newcommand{\OtherTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textbf{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{#1}
\newcommand{\SpecialStringTok}[1]{#1}
\newcommand{\StringTok}[1]{#1}
\newcommand{\VariableTok}[1]{#1}
\newcommand{\VerbatimStringTok}[1]{#1}
\newcommand{\WarningTok}[1]{\textit{#1}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\usepackage{float}
\usepackage{wrapfig}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Analyse de la perception des espace vert de la ville de Parakou par ses habitant},
  pdfauthor={GANDAHO GENIEL I.M.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analyse de la perception des espace vert de la ville de Parakou
par ses habitant}
\author{GANDAHO GENIEL I.M.}
\date{2024-11-01}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{6}
\tableofcontents
}
\subsection{statistique descriptif}\label{statistique-descriptif}

\subsubsection{Interpretation des moyenne
Age}\label{interpretation-des-moyenne-age}

Moyenne etant de \textbf{1.73} il revient ains de dire que le individue
enquete sont majoritairement constituer de personne age de \textbf{18
ans a 30 ans}

\subsubsection{Interpretation des moyenne
sexe}\label{interpretation-des-moyenne-sexe}

Moyenne etant de \textbf{1.51} il revient ains de dire que le individue
enquete sont majoritairement constituer d' \textbf{Hommes}

\subsubsection{Interpretation des moyenne frequence de
visite.}\label{interpretation-des-moyenne-frequence-de-visite.}

Moyenne etant de \textbf{3.39} et proche de la mediane cela suggere donc
que la majoriter des enqueter visite de maniere moderer les espace vert

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{describe}\NormalTok{(df3\_numeriq ,}\AttributeTok{num.desc =} \FunctionTok{c}\NormalTok{(}\StringTok{"mean"}\NormalTok{,}\StringTok{"sd"}\NormalTok{,}\StringTok{"min"}\NormalTok{, }\StringTok{"max"}\NormalTok{, }\StringTok{"valid.n"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Description of df3_numeriq
\end{verbatim}

\begin{verbatim}
## 
##  Numeric 
##                                mean   sd min max valid.n
## autreprofessionr               3.14 0.77   1   5      22
## raison_non_visiter             2.06 0.95   1   3      32
## espace_visiter                 5.46 4.20   1  12      70
## activite_generaler             5.03 2.16   1  11      70
## benefices_espaces_vertsr       3.47 1.99   1   8      70
## evaluation_etat_espaces_vertsr 2.66 0.76   1   4      70
## sexer                          1.51 0.50   1   2     102
## ager                           1.73 0.92   1   4     102
## frequence_visiter              3.39 2.02   1   6     102
## niveau_educationr              2.51 0.56   1   3     102
## professionr                    3.32 1.20   1   5     102
## participation_initiativesr     2.70 0.52   1   3     102
## implication_autoritesr         2.33 0.51   1   3     102
## implication_communauter        2.28 0.93   1   3     102
\end{verbatim}

\subsection{Repartition Sexuel}\label{repartition-sexuel}

l'analyse de graphique et du graphique ci dessous montre que la
population enquete composer de 102 individu est compose de 50 femme soit
un pourcentage de 49.02 \% et 52 Hommes pour un pourcentage de 50.98 \%

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sexe}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{sexe}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{sexe}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Femme}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{50}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{49.02}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Homme}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{52}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{50.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{repartion par sexe}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Analyse-de-la-perception2_files/figure-latex/repartition par sexe-1.pdf}

\subsection{Repartition par Age}\label{repartition-par-age}

la population enqueter majoritairement contituer de d'individue age de
18 ans a 45 ans soit un pourcentage de \textbf{50.98 \%} age de 18 a 30
ans et \textbf{34.31 \%} age de 31 a 45 ans. Enfin minoritairement
composer pour un pourcentage de \textbf{8.82 \%} pour les individue de
moins de 18 ans et \textbf{5.88 \%} pour ceux age de 46 ans a 60 ans

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{age}
\end{Highlighting}
\end{Shaded}

\includegraphics{Analyse-de-la-perception2_files/figure-latex/Age-1.pdf}

\subsection{Repartion des espace visiter dans la ville de
parakou}\label{repartion-des-espace-visiter-dans-la-ville-de-parakou}

De lanalyse de ce graphique il peut etre retenue que les preference des
enqueter en terme de d'espace vert se tourne beaucoup plus plus vers 3
espace vert que sont \textbf{BIO GUERRA} (19/102 enqueter),
\textbf{PAPINI} (16/102 enqueter) et \textbf{COTEB} (12/102 enqueter) on
peut donc deduire que celle ci ont plus d'afluence que les autre espace
vert.

Il est important notifier que COTEB en terme de preference peut etre
associer a d'autre d'autre espace vert telle que HUBERT MAGA(3/102
enqueter), FORET(3/102 enqueter) de meme que BIO GUERRE souvent associer
a PAPINI(5/102 enqueter)

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{espace visite}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Analyse-de-la-perception2_files/figure-latex/espace visiter-1.pdf}

\subsection{Frequence de visite}\label{frequence-de-visite}

\subsubsection{Interprétation des Fréquences de
Visite}\label{interpruxe9tation-des-fruxe9quences-de-visite}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Jamais (31,37\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 32 personnes
  \item
    \textbf{Interprétation} : Un peu plus d'un tiers des répondants
    déclarent ne jamais visiter les espaces verts. Cela peut indiquer un
    manque d'intérêt, d'accès ou de sensibilisation sur les bénéfices
    des espaces verts.
  \end{itemize}
\item
  \textbf{Plusieurs fois par semaine (7,84\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 8 personnes
  \item
    \textbf{Interprétation} : Une très faible proportion de répondants
    visite les espaces verts plusieurs fois par semaine, ce qui peut
    suggérer que ces espaces ne sont pas perçus comme des lieux
    attrayants ou accessibles.
  \end{itemize}
\item
  \textbf{Rarement (15,69\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 16 personnes
  \item
    \textbf{Interprétation} : Ce groupe représente une proportion
    modérée. Les raisons peuvent inclure des contraintes de temps ou des
    alternatives perçues comme plus attrayantes.
  \end{itemize}
\item
  \textbf{Tous les jours (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Très peu de personnes visitent les espaces
    verts quotidiennement, ce qui souligne peut-être un manque de temps
    ou de proximité.
  \end{itemize}
\item
  \textbf{Une fois par mois (19,61\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 20 personnes
  \item
    \textbf{Interprétation} : Une proportion significative de répondants
    se rend aux espaces verts au moins une fois par mois, ce qui indique
    une certaine utilisation, mais pas de manière régulière.
  \end{itemize}
\item
  \textbf{Une fois par semaine (22,55\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 23 personnes
  \item
    \textbf{Interprétation} : Cette catégorie regroupe une part notable
    des répondants, ce qui peut refléter un usage modéré des espaces
    verts. Cela montre que certains individus intègrent ces visites dans
    leur routine hebdomadaire.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion}

Le tableau des fréquences de visite met en lumière plusieurs
comportements. \textbf{Près de 31,37\% des répondants n'utilisent pas du
tout les espaces verts}, tandis qu'une part significative (22,55\%) les
visite une fois par semaine. Cela indique qu'il pourrait être bénéfique
de mener des actions de sensibilisation et d'amélioration des
infrastructures pour encourager une fréquentation plus élevée des
espaces verts.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{frequence de visite}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{frequence\_visite}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{frequence\_visite}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Jamais}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.37}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Plusieurs\ fois\ par\ semaine}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{8}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{7.84}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Rarement}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{16}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{15.69}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Tous\ les\ jours}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Une\ fois\ par\ mois}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{20}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{19.61}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Une\ fois\ par\ semaine}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{23}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{22.55}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Niveau education}\label{niveau-education}

\subsubsection{Interprétation des Niveaux
d'Éducation}\label{interpruxe9tation-des-niveaux-duxe9ducation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Primaire (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Une très faible proportion des répondants
    (moins de 3\%) a atteint le niveau primaire. Cela peut indiquer que
    la population ciblée est majoritairement composée de personnes ayant
    poursuivi leur éducation au-delà de ce niveau.
  \end{itemize}
\item
  \textbf{Secondaire (43,14\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 44 personnes
  \item
    \textbf{Interprétation} : Près de 43\% des répondants ont un niveau
    d'éducation secondaire. Cela représente une part importante et
    pourrait indiquer que le secondaire est un niveau d'éducation
    relativement courant parmi cette population.
  \end{itemize}
\item
  \textbf{Universitaire (53,92\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 55 personnes
  \item
    \textbf{Interprétation} : Plus de la moitié des répondants (53,92\%)
    ont un niveau d'éducation universitaire. Cela suggère que la
    population est majoritairement instruite et pourrait avoir des
    attentes élevées en matière de services et d'aménagements.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-1}

Les données sur le niveau d'éducation révèlent une majorité de
répondants ayant un niveau universitaire (53,92\%), suivi par ceux ayant
un niveau secondaire (43,14\%). \textbf{La faible proportion de
personnes ayant un niveau primaire (2,94\%) suggère que les répondants
ont généralement ete a l'ecole}.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{niveau de education des enqueter}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{niveau\_education}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{niveau\_education}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Primaire}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Secondaire}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{44}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{43.14}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Universitaire}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{55}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{53.92}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Profession}\label{profession}

\subsubsection{Interprétation des
Professions}\label{interpruxe9tation-des-professions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Agriculteur (6,86\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 7 personnes
  \item
    \textbf{Interprétation} : Une petite proportion des répondants se
    décrit comme agriculteur. Cela pourrait indiquer que l'agriculture
    n'est pas la principale source de revenu dans cette population ou
    qu'elle est moins représentée dans l'échantillon.
  \end{itemize}
\item
  \textbf{Autre (préciser) (21,57\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 22 personnes
  \item
    \textbf{Interprétation} : Une proportion significative de répondants
    (21,57\%) a choisi la catégorie ``Autre''. Cela pourrait suggérer
    une diversité de professions, qui pourrait inclure des métiers moins
    courants ou des professions non spécifiées. Une analyse qualitative
    de cette catégorie pourrait fournir des informations précieuses.
  \end{itemize}
\item
  \textbf{Commerçant (22,55\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 23 personnes
  \item
    \textbf{Interprétation} : Les commerçants représentent une part
    importante (22,55\%) de la population. Cela peut indiquer une
    économie locale dynamique où le commerce joue un rôle crucial.
  \end{itemize}
\item
  \textbf{Fonctionnaire (18,63\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 19 personnes
  \item
    \textbf{Interprétation} : Une proportion notable de répondants
    (18,63\%) est fonctionnaire, ce qui peut refléter une structure
    d'emploi dans le secteur public relativement importante dans la
    communauté.
  \end{itemize}
\item
  \textbf{Étudiant (30,39\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 31 personnes
  \item
    \textbf{Interprétation} : La plus grande catégorie est celle des
    étudiants, représentant 30,39\% des répondants. Cela indique une
    forte concentration de jeunes en formation, ce qui peut influencer
    les attentes en matière de services et d'infrastructures.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-2}

La répartition professionnelle montre une diversité parmi les
répondants, avec une majorité d'étudiants (30,39\%) suivie par des
commerçants (22,55\%) et d'autres professions (21,57\%).
\textbf{L'absence d'une forte représentation des agriculteurs pourrait
suggérer un urbanisme plus développé ou un changement dans les
dynamiques économiques locales.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{profession}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{profession}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{profession}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Agriculteur}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{7}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6.86}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Autre\ (préciser)}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{22}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{21.57}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Commerçant}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{23}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{22.55}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Fonctionnaire}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{19}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{18.63}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Étudiant}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{30.39}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Activite en generale}\label{activite-en-generale}

\subsubsection{Interprétation des Activités
Générales}\label{interpruxe9tation-des-activituxe9s-guxe9nuxe9rales}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{PROMENADE (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Une faible proportion des répondants se
    consacre uniquement à la promenade. Cela peut indiquer que cette
    activité est souvent combinée avec d'autres, plutôt que pratiquée
    isolément.
  \end{itemize}
\item
  \textbf{PROMENADE/SPORT (1,96\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 2 personnes
  \item
    \textbf{Interprétation} : Encore une fois, très peu de répondants
    (moins de 2\%) pratiquent la promenade combinée avec le sport. Cela
    pourrait refléter un faible intérêt pour cette combinaison
    d'activités.
  \end{itemize}
\item
  \textbf{PROMENADE/OBSERVATION (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Cette combinaison est également peu
    courante, suggérant que les répondants préfèrent des activités plus
    interactives ou engagées.
  \end{itemize}
\item
  \textbf{PROMENADE/LECTURE (34,31\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 35 personnes
  \item
    \textbf{Interprétation} : Cette catégorie représente la majorité des
    répondants (34,31\%). Cela indique que la lecture est une activité
    populaire parmi ceux qui fréquentent les espaces verts, peut-être en
    raison de l'environnement calme et relaxant qu'ils offrent.
  \end{itemize}
\item
  \textbf{AUTRE (5,88\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 6 personnes
  \item
    \textbf{Interprétation} : Une petite portion des répondants a
    mentionné des activités non spécifiées, ce qui pourrait refléter une
    variété d'autres loisirs ou pratiques.
  \end{itemize}
\item
  \textbf{PROMENADE/SPORT/ETUDE (3,92\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 4 personnes
  \item
    \textbf{Interprétation} : Cette combinaison montre un intérêt pour
    une approche multidisciplinaire, mais reste minoritaire.
  \end{itemize}
\item
  \textbf{PROMENADE/PICNIC (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : La faible représentation des pique-niques
    pourrait indiquer un manque d'infrastructure ou d'espace approprié
    pour cette activité.
  \end{itemize}
\item
  \textbf{PROMENADE/LECTURE/PICNIC (11,76\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 12 personnes
  \item
    \textbf{Interprétation} : Une proportion intéressante de répondants
    combine lecture et pique-nique, suggérant que certains fréquentent
    les espaces verts pour des moments de détente.
  \end{itemize}
\item
  \textbf{PROMENADE/SPORT/ETUDE/OBSERVATION (1,96\%)} et autres
  combinaisons :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Interprétation} : Les activités combinant plusieurs éléments
    sont très peu représentées, ce qui pourrait indiquer que les
    répondants préfèrent se concentrer sur une ou deux activités à la
    fois.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-3}

Les résultats montrent que la \textbf{lecture} en promenade est
l'activité la plus courante (34,31\%), suivie par des combinaisons moins
fréquentes d'activités. \textbf{Les pique-niques et les activités
combinant plusieurs éléments sont peu pratiqués, ce qui pourrait
signaler un besoin d'infrastructure ou d'espaces adaptés pour ces
loisirs.}

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{activiite en generale}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{activite\_generale}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{activite\_generale}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/SPORT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1.96}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/OBSERVATION}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/LECTURE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{35}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{34.31}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{AUTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{5.88}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/SPORT/ETUDE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{4}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3.92}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/PICNIC}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/LECTURE/PICNIC}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{12}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{11.76}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/SPORT/ETUDE/OBSERVATION}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1.96}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/LECTURE/OBSERVATION}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{PROMENADE/LECTURE/SPORT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.37}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{99.98}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Benefice des espaces vert}\label{benefice-des-espaces-vert}

\subsubsection{Interprétation des Bénéfices des Espaces
Verts}\label{interpruxe9tation-des-buxe9nuxe9fices-des-espaces-verts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Détente (5,88\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 6 personnes
  \item
    \textbf{Interprétation} : Une faible proportion de répondants
    mentionne la détente comme unique bénéfice. Cela pourrait indiquer
    que, même si la détente est appréciée, elle est souvent associée à
    d'autres activités ou bénéfices.
  \end{itemize}
\item
  \textbf{Détente/Rencontre (27,45\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 28 personnes
  \item
    \textbf{Interprétation} : Ce groupe représente la majorité des
    répondants. Cela suggère que les usagers des espaces verts
    perçoivent ces lieux principalement comme des endroits pour se
    détendre tout en socialisant, soulignant l'importance des
    interactions sociales dans ces environnements.
  \end{itemize}
\item
  \textbf{Rencontre (8,82\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 9 personnes
  \item
    \textbf{Interprétation} : Un pourcentage significatif des répondants
    considère les espaces verts comme des lieux de rencontre. Cependant,
    ce chiffre est inférieur à ceux qui combinent détente et rencontre,
    indiquant que la détente est un facteur clé lors des rencontres.
  \end{itemize}
\item
  \textbf{Détente/Rencontre/Réduction du bruit (6,86\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 7 personnes
  \item
    \textbf{Interprétation} : Cette combinaison souligne que certains
    usagers voient les espaces verts comme des refuges non seulement
    pour se détendre et rencontrer des gens, mais aussi pour échapper au
    bruit environnant.
  \end{itemize}
\item
  \textbf{Détente/Réduction du bruit (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : Très peu de répondants voient uniquement
    la détente et la réduction du bruit comme bénéfices. Cela peut
    indiquer que ces avantages sont perçus comme moins prioritaires par
    rapport à d'autres.
  \end{itemize}
\item
  \textbf{Autre (14,71\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 15 personnes
  \item
    \textbf{Interprétation} : Une proportion notable de répondants a
    mentionné d'autres bénéfices non spécifiés. Cela pourrait refléter
    la diversité des expériences et des préférences des usagers.
  \end{itemize}
\item
  \textbf{Réduction du bruit (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : Seul un répondant a identifié la réduction
    du bruit comme un bénéfice distinct, ce qui pourrait suggérer que,
    bien que cela soit important, ce n'est pas le principal attrait des
    espaces verts pour la plupart des usagers.
  \end{itemize}
\item
  \textbf{Rencontre/Réduction du bruit (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Quelques répondants voient une combinaison
    de rencontres et de réduction du bruit comme un bénéfice, soulignant
    une possible recherche d'un environnement calme pour socialiser.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-4}

Les résultats montrent que les \textbf{usagers des espaces verts
valorisent principalement la combinaison de la détente et des rencontres
(27,45\%)}. Les autres bénéfices, comme la réduction du bruit, sont
moins souvent cités comme des priorités.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{benefices des espace vert}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{benefices\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{benefices\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{5.88}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/RENCONTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{28}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{27.45}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{RENCONTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{9}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{8.82}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/RENCONTRE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{7}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6.86}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{AUTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{15}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{14.71}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{RENCONTRE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.37}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{99.99}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Raison de non visite}\label{raison-de-non-visite}

\subsubsection{Interprétation des Raisons de Non-Visite des Espaces
Verts}\label{interpruxe9tation-des-raisons-de-non-visite-des-espaces-verts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Absence d'espace vert près de chez moi (12,75\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 13 personnes
  \item
    \textbf{Interprétation} : Une proportion significative de répondants
    indique que l'absence d'espaces verts à proximité de leur domicile
    est un facteur limitant. Cela souligne l'importance de la
    localisation des espaces verts pour encourager leur utilisation. Les
    planificateurs pourraient envisager d'améliorer l'accès en créant de
    nouveaux espaces verts dans des zones moins desservies.
  \end{itemize}
\item
  \textbf{Manque d'intérêt (3,92\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 4 personnes
  \item
    \textbf{Interprétation} : Un petit nombre de répondants ne montrent
    pas d'intérêt pour les espaces verts. Cela pourrait refléter une
    méconnaissance des bénéfices des espaces verts ou un manque de
    motivation. Des initiatives de sensibilisation pourraient être
    utiles pour encourager une plus grande appréciation des avantages
    associés à ces espaces.
  \end{itemize}
\item
  \textbf{Manque de temps (14,71\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 15 personnes
  \item
    \textbf{Interprétation} : Cette raison est la plus fréquemment citée
    parmi celles fournies. Un manque de temps peut être un obstacle
    majeur à la visite des espaces verts, indiquant que les usagers sont
    souvent occupés par d'autres engagements. Cela peut également
    refléter un style de vie urbain où les horaires sont chargés. Les
    planificateurs pourraient envisager d'organiser des événements à des
    moments qui conviennent mieux aux résidents pour faciliter leur
    participation.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-5}

Les résultats montrent que \textbf{le manque de temps (14,71\%)} est la
principale raison citée pour ne pas visiter les espaces verts, suivie de
l'absence d'espace vert à proximité (12,75\%). Le manque d'intérêt
représente une préoccupation mineure.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{raison de non visite}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{raison\_non\_visite}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{raison\_non\_visite}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Absence\ d'espace\ vert\ près\ de\ chez\ moi}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{13}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{12.75}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Manque\ d'intérêt}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{4}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3.92}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Manque\ de\ temps}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{15}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{14.71}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.38}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Evaluation Espace vert}\label{evaluation-espace-vert}

\subsubsection{Interprétation de l'Évaluation de l'État des Espaces
Verts}\label{interpruxe9tation-de-luxe9valuation-de-luxe9tat-des-espaces-verts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{État Moyen (53,92\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 55 personnes
  \item
    \textbf{Interprétation} : La majorité des répondants (plus de la
    moitié) évaluent l'état des espaces verts comme moyen. Cela indique
    qu'il y a des attentes non satisfaites concernant la qualité et
    l'entretien de ces espaces. Les planificateurs devraient prendre
    cela en compte en mettant en œuvre des actions d'amélioration pour
    rehausser la qualité des espaces verts et répondre aux attentes des
    usagers.
  \end{itemize}
\item
  \textbf{État Bon (10,78\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 11 personnes
  \item
    \textbf{Interprétation} : Un nombre relativement faible d'usagers
    considère l'état des espaces verts comme bon. Cela suggère que bien
    qu'il y ait quelques espaces qui répondent aux attentes, il existe
    un besoin général d'amélioration. Les responsables devraient
    identifier ces espaces et examiner ce qui contribue à leur bonne
    évaluation pour éventuellement reproduire ces caractéristiques
    ailleurs.
  \end{itemize}
\item
  \textbf{État Mauvais (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Seule une petite proportion des répondants
    évalue l'état des espaces verts comme mauvais. Cela pourrait
    indiquer des espaces spécifiques qui nécessitent une attention
    immédiate en termes de nettoyage, de maintenance ou de sécurité.
  \end{itemize}
\item
  \textbf{État Très Bon (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : Très peu d'usagers (1 personne) jugent
    l'état des espaces verts comme très bon. Cela souligne que, malgré
    quelques exemples positifs, il y a une perception généralisée que la
    majorité des espaces verts pourrait être nettement améliorée.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-6}

La majorité des répondants évalue l'état des espaces verts comme moyen
(53,92\%), ce qui souligne des opportunités d'amélioration
significatives. Les espaces jugés bons sont peu nombreux, tandis que
quelques-uns sont considérés comme mauvais.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{evaluation des espace vert}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{evaluation\_etat\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{evaluation\_etat\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Bon}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{11}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{10.78}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Mauvais}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Moyen}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{55}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{53.92}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Très\ bon}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.37}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{99.99}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Participation initiative}\label{participation-initiative}

\subsubsection{Interprétation de la Participation aux
Initiatives}\label{interpruxe9tation-de-la-participation-aux-initiatives}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Peut-être (72,55\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 74 personnes
  \item
    \textbf{Interprétation} : Une large majorité des répondants
    (72,55\%) indique une position indécise quant à leur participation
    aux initiatives. Cela peut refléter un intérêt potentiel mais aussi
    un manque d'informations ou de clarté sur la nature de ces
    initiatives. Les planificateurs devraient s'interroger sur les
    raisons de cette hésitation, notamment en évaluant les obstacles
    perçus ou le manque de sensibilisation.
  \end{itemize}
\item
  \textbf{Oui (24,51\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 25 personnes
  \item
    \textbf{Interprétation} : Environ un quart des répondants exprime un
    intérêt clair pour participer aux initiatives. Cela représente une
    opportunité pour les planificateurs d'engager activement ces
    individus en leur fournissant des rôles concrets et en les
    impliquant dans la planification et l'exécution des initiatives.
  \end{itemize}
\item
  \textbf{Non (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Un faible nombre de répondants (2,94\%)
    refuse catégoriquement de participer aux initiatives. Cela pourrait
    indiquer une désaffection ou une perception négative envers les
    initiatives en cours. Il est essentiel pour les planificateurs de
    comprendre les raisons de cette position afin de rectifier ou
    d'améliorer les initiatives proposées.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-7}

La majorité des répondants se trouve dans une position intermédiaire
d'incertitude, avec un intérêt potentiel pour la participation, tandis
qu'un quart est prêt à s'engager. Cela souligne la nécessité d'une
stratégie de communication et d'engagement plus ciblée.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{participation au initiative}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{participation\_initiatives}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{participation\_initiatives}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Non}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Oui}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{25}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{24.51}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Peut-être}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{74}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{72.55}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Implication Autoriter}\label{implication-autoriter}

\subsubsection{Interprétation de l'Implication des
Autorités}\label{interpruxe9tation-de-limplication-des-autorituxe9s}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Non (62,75\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 64 personnes
  \item
    \textbf{Interprétation} : Une majorité écrasante des répondants
    (62,75\%) estime que les autorités ne sont pas impliquées dans les
    initiatives. Cela peut indiquer un manque de visibilité ou de
    communication concernant le rôle des autorités dans ces projets, ou
    une perception que leur soutien est insuffisant. Il serait crucial
    d'explorer les raisons derrière cette perception, car une faible
    implication des autorités peut nuire à la légitimité et au succès
    des initiatives.
  \end{itemize}
\item
  \textbf{Oui (35,29\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 36 personnes
  \item
    \textbf{Interprétation} : Un tiers des répondants reconnaît une
    certaine forme d'implication des autorités. Cela peut signifier que,
    bien que leur présence soit notée, il pourrait y avoir un besoin
    d'augmenter cette implication pour renforcer la confiance et
    l'engagement de la communauté. Les planificateurs devraient
    identifier les types d'implications perçues et les occasions où les
    autorités ont été actives pour mieux promouvoir ces actions.
  \end{itemize}
\item
  \textbf{Ne sait pas (1,96\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 2 personnes
  \item
    \textbf{Interprétation} : Un nombre très faible de répondants
    (1,96\%) ne sait pas si les autorités sont impliquées. Cela peut
    indiquer un manque de sensibilisation ou d'information sur le rôle
    des autorités dans les initiatives. Les planificateurs devraient
    viser à améliorer la communication autour de l'engagement des
    autorités pour éclairer ceux qui ne sont pas informés.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-8}

Les résultats montrent un fort sentiment que les autorités sont absentes
des initiatives, ce qui pourrait poser des défis à l'engagement
communautaire.

\subsubsection{Interprétation de l'Implication de la
Communauté}\label{interpruxe9tation-de-limplication-de-la-communautuxe9}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Peu impliquée (60,78\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 62 personnes
  \item
    \textbf{Interprétation} : Une majorité significative des répondants
    (60,78\%) estime que la communauté est peu impliquée dans les
    initiatives. Cela pourrait refléter un manque d'engagement,
    d'information ou d'opportunités pour que les membres de la
    communauté participent activement. Les planificateurs doivent
    identifier les obstacles qui empêchent une plus grande implication
    et développer des stratégies pour encourager une participation plus
    active.
  \end{itemize}
\item
  \textbf{Impliquée (32,35\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 33 personnes
  \item
    \textbf{Interprétation} : Environ un tiers des répondants (32,35\%)
    se sentent impliqués dans les initiatives. Cela indique qu'il existe
    un groupe de membres de la communauté qui sont prêts à participer et
    s'engager. Les planificateurs devraient capitaliser sur cet intérêt
    en offrant des opportunités pour que ces individus prennent des
    rôles de leadership ou de facilitation au sein des initiatives.
  \end{itemize}
\item
  \textbf{Pas du tout impliquée (6,86\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 7 personnes
  \item
    \textbf{Interprétation} : Un petit nombre de répondants (6,86\%)
    indique que la communauté n'est pas du tout impliquée. Bien que ce
    chiffre soit faible, il est essentiel de comprendre les raisons
    derrière cette position afin d'ajuster les initiatives et d'adresser
    les préoccupations spécifiques de ces membres.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-9}

Les résultats soulignent une perception dominante que la communauté est
peu impliquée dans les initiatives, ce qui pourrait constituer un défi
pour l'efficacité de ces projets.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{implication autauriter}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{implication\_autorites}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{implication\_autorites}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Ne\ sait\ pas}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1.96}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Non}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{64}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{62.75}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Oui}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{36}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{35.29}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{100.00}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{implication communauter}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{implication\_communaute}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{implication\_communaute}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Impliquée}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{33}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32.35}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Pas\ du\ tout\ impliquée}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{7}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6.86}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Peu\ impliquée}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{62}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{60.78}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{99.99}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Benefice espace vert}\label{benefice-espace-vert}

\subsubsection{Interprétation des Bénéfices des Espaces
Verts}\label{interpruxe9tation-des-buxe9nuxe9fices-des-espaces-verts-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Détente (5,88\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 6 personnes
  \item
    \textbf{Interprétation} : Une petite proportion des répondants
    considère que le principal bénéfice des espaces verts est la
    détente. Cela peut indiquer que bien que la détente soit reconnue
    comme un avantage, elle n'est pas perçue comme le bénéfice le plus
    important, ce qui peut signaler une opportunité d'amélioration dans
    la promotion de cet aspect.
  \end{itemize}
\item
  \textbf{Détente/Rencontre (27,45\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 28 personnes
  \item
    \textbf{Interprétation} : Près d'un tiers des répondants (27,45\%)
    perçoivent les espaces verts comme des lieux de détente et de
    rencontre. Cela souligne l'importance des espaces verts comme des
    lieux sociaux où les individus peuvent se rassembler et interagir,
    favorisant ainsi le lien social au sein de la communauté.
  \end{itemize}
\item
  \textbf{Rencontre (8,82\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 9 personnes
  \item
    \textbf{Interprétation} : Un pourcentage notable de répondants
    (8,82\%) valorise la fonction des espaces verts en tant que lieux de
    rencontre. Cela peut indiquer une reconnaissance de l'importance de
    l'interaction sociale dans ces espaces, bien que cette perception
    soit inférieure à celle des bénéfices combinés de détente et de
    rencontre.
  \end{itemize}
\item
  \textbf{Détente/Rencontre/Réduction du bruit (6,86\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 7 personnes
  \item
    \textbf{Interprétation} : Ce groupe souligne un bénéfice
    multifonctionnel des espaces verts, où les répondants voient une
    synergie entre détente, rencontre et réduction du bruit, ce qui
    renforce l'idée que ces espaces peuvent jouer un rôle essentiel dans
    l'amélioration de la qualité de vie.
  \end{itemize}
\item
  \textbf{Détente/Réduction du bruit (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : Ce bénéfice est très peu mentionné, ce qui
    peut indiquer que les répondants ne perçoivent pas la réduction du
    bruit comme un avantage majeur des espaces verts.
  \end{itemize}
\item
  \textbf{Autre (14,71\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 15 personnes
  \item
    \textbf{Interprétation} : Un nombre significatif de répondants a
    mentionné d'autres bénéfices, ce qui pourrait signaler une variété
    de perceptions et d'attentes non couvertes par les catégories
    proposées. Cela mérite une attention particulière pour explorer ces
    bénéfices supplémentaires.
  \end{itemize}
\item
  \textbf{Réduction du bruit (0,98\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 1 personne
  \item
    \textbf{Interprétation} : La faible mention de la réduction du bruit
    comme bénéfice indique qu'il pourrait être moins reconnu par les
    utilisateurs d'espaces verts, ce qui pourrait suggérer une
    opportunité d'amélioration pour les concepteurs d'espaces publics.
  \end{itemize}
\item
  \textbf{Rencontre/Réduction du bruit (2,94\%)} :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Effectif} : 3 personnes
  \item
    \textbf{Interprétation} : Bien que ce groupe soit peu représenté, il
    indique qu'il existe une prise de conscience des bénéfices combinés
    de ces espaces.
  \end{itemize}
\end{enumerate}

\subsubsection{Conclusion}\label{conclusion-10}

Les résultats montrent que les répondants perçoivent principalement les
espaces verts comme des lieux favorisant la détente et les rencontres,
mais il existe également un intérêt pour d'autres bénéfices qui méritent
d'être explorés.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{benefices des espace vert}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: fonts used in `flextable` are ignored because the `pdflatex` engine is
## used and not `xelatex` or `lualatex`. You can avoid this warning by using the
## `set_flextable_defaults(fonts_ignore=TRUE)` command or use a compatible engine
## by defining `latex_engine: xelatex` in the YAML header of the R Markdown
## document.
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{benefices\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{benefices\_espaces\_verts}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Effectif}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\textbf{Pourcentage\%}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{5.88}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/RENCONTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{28}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{27.45}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{RENCONTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{9}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{8.82}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/RENCONTRE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{7}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{6.86}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{DETENTE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{AUTRE}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{15}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{14.71}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{1}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.98}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{RENCONTRE/REDUCTION\ BRUIT}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{2.94}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{32}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{31.37}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Total}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{102}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{99.99}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Correlation en les
variable}\label{correlation-en-les-variable}

Interprétation du Heatmap des Corrélations Le graphique fourni est un
heatmap qui montre les coefficients de corrélation entre différentes
variables relatives à l'implication communautaire, au niveau
d'éducation, à la fréquence de visites, à l'âge, au sexe, à l'évaluation
des espaces verts, aux bénéfices des espaces verts, à l'activité
générale, et aux raisons pour lesquelles certaines personnes ne visitent
pas les espaces.

\#\#Observations Clés : 1. \textbf{Corrélations Négatives Fortes :}

implication\_communauter et implication\_autoriser : Un coefficient de
corrélation de -0.82 suggère une forte corrélation négative entre ces
deux variables. Cela pourrait indiquer que lorsque l'implication
communautaire augmente, l'implication autorisée diminue
significativement, ou vice versa.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Corrélations Positives Fortes :}
\end{enumerate}

\begin{itemize}
\item
  \textbf{espace\_visiter et autreprofesionr :} Un coefficient de
  corrélation de 1 indique une corrélation positive parfaite entre ces
  deux variables. Cela pourrait signifier que les professionnels ont
  tendance à visiter les espaces plus fréquemment.
\item
  \textbf{evaluation\_etat\_espaces\_vertsr et
  benefices\_espaces\_vertsr :} Un coefficient de corrélation de 1
  montre une corrélation positive parfaite, suggérant que ceux qui
  évaluent bien l'état des espaces verts perçoivent également des
  bénéfices significatifs de ces espaces.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Corrélations Modérées à Faibles} :
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \textbf{sexer et autreprofesionr :} Une corrélation négative de -0.38
  montre une relation inverse modérée entre le sexe et la profession.
  Cela pourrait indiquer que certaines professions sont dominées par un
  sexe particulier.
\end{itemize}

\subsubsection{Implications Pratiques :}\label{implications-pratiques}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Implication Communautaire et Autorisée :}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Les efforts visant à augmenter l'implication communautaire doivent
  tenir compte de son impact potentiel sur l'implication autorisée et
  vice versa.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Espaces Visités et Profession :}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Les campagnes de promotion des espaces verts pourraient cibler des
  groupes professionnels spécifiques pour augmenter la fréquentation.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Evaluation des Espaces Verts :}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Améliorer l'état des espaces verts pourrait directement augmenter la
  perception des bénéfices par les utilisateurs.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \textbf{Genre et Profession :}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Les politiques de diversité de genre dans certaines professions
  pourraient influencer la fréquentation des espaces verts.
\end{itemize}

\subsubsection{Conclusion}\label{conclusion-11}

Ce heatmap des corrélations permet de visualiser rapidement les
relations entre différentes variables, facilitant ainsi l'identification
des corrélations fortes ou faibles qui peuvent guider les décisions
stratégiques. Utiliser ces informations peut aider à mieux comprendre
les dynamiques entre différentes caractéristiques et comportements des
utilisateurs dans le contexte de l'implication communautaire et de
l'utilisation des espaces verts.

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{\textasciigrave{}}\AttributeTok{correlation entre variable}\StringTok{\textasciigrave{}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Analyse-de-la-perception2_files/figure-latex/heatmap de corelation-1.pdf}

\subsection{Conclusion Finale sur le Projet d'Analyse des Espaces
Verts}\label{conclusion-finale-sur-le-projet-danalyse-des-espaces-verts}

Ce projet d'analyse a permis d'explorer la perception des utilisateurs
concernant les espaces verts dans la commune. À travers une collecte de
données qualitative et quantitative, nous avons pu dégager des
informations cruciales sur les motivations, les attentes et les
comportements des usagers. Voici les points clés qui émergent de cette
étude :

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Importance des Espaces Verts} : Les espaces verts sont perçus
  comme essentiels pour le bien-être des citoyens, principalement en
  tant que lieux de détente et de rencontre. Cela souligne la nécessité
  de maintenir et de développer ces espaces pour favoriser la santé
  mentale et sociale de la communauté.
\item
  \textbf{Bénéfices Multifonctionnels} : Les résultats montrent que les
  usagers reconnaissent plusieurs bénéfices associés aux espaces verts,
  notamment la détente, la réduction du bruit et les interactions
  sociales. Cela indique que ces lieux jouent un rôle multifonctionnel
  dans la vie quotidienne des citoyens.
\item
  \textbf{Perceptions Variées} : Il existe une diversité d'opinions
  concernant l'utilisation et l'accessibilité des espaces verts.
  Certains utilisateurs ont exprimé des préoccupations quant à l'absence
  d'espaces adéquats et au manque d'intérêt pour les activités
  proposées. Cela démontre l'importance d'écouter et de répondre aux
  besoins variés des membres de la communauté.
\item
  \textbf{Rôle des Autorités et de la Communauté} : L'analyse révèle que
  l'implication des autorités et des communautés est cruciale pour le
  succès des initiatives liées aux espaces verts. Les résultats
  indiquent un manque d'engagement de certaines autorités, ce qui
  pourrait nuire à l'entretien et à la promotion de ces espaces.
\item
  \textbf{Recommendations pour l'Amélioration} : Sur la base des
  résultats, plusieurs recommandations peuvent être formulées pour
  améliorer l'accès et la qualité des espaces verts :

  \begin{itemize}
  \tightlist
  \item
    \textbf{Aménagement participatif} : Impliquer les citoyens dans le
    processus de planification et d'aménagement des espaces verts pour
    répondre à leurs besoins spécifiques.
  \item
    \textbf{Programmes de sensibilisation} : Développer des programmes
    éducatifs visant à promouvoir l'utilisation des espaces verts et
    leurs bénéfices.
  \item
    \textbf{Augmenter l'accessibilité} : Identifier et éliminer les
    obstacles qui empêchent l'accès aux espaces verts, notamment en
    améliorant les infrastructures de transport et en créant des espaces
    adaptés pour tous.
  \end{itemize}
\end{enumerate}

\subsection{Conclusion Globale}\label{conclusion-globale}

Ce projet met en lumière l'importance cruciale des espaces verts dans le
tissu social et le bien-être des citoyens. Les résultats obtenus
appellent à une action concertée de la part des autorités locales et de
la communauté pour garantir que ces espaces continuent de servir de
refuges et de lieux d'interaction sociale. En intégrant les suggestions
et en répondant aux préoccupations des utilisateurs, nous pouvons
améliorer la qualité de vie au sein de notre commune et favoriser un
environnement sain et inclusif.

\end{document}
